import { UiohookKey } from "uiohook-napi";

/** Имя клавиши из HotkeysConfig → keycode uIOhook. */
export function hotkeyNameToCode(name: string): number | null {
  const n = name.trim();
  if (!n) return null;

  const table: Record<string, number> = {
    A: UiohookKey.A,
    B: UiohookKey.B,
    C: UiohookKey.C,
    D: UiohookKey.D,
    E: UiohookKey.E,
    F: UiohookKey.F,
    G: UiohookKey.G,
    H: UiohookKey.H,
    I: UiohookKey.I,
    J: UiohookKey.J,
    K: UiohookKey.K,
    L: UiohookKey.L,
    M: UiohookKey.M,
    N: UiohookKey.N,
    O: UiohookKey.O,
    P: UiohookKey.P,
    Q: UiohookKey.Q,
    R: UiohookKey.R,
    S: UiohookKey.S,
    T: UiohookKey.T,
    U: UiohookKey.U,
    V: UiohookKey.V,
    W: UiohookKey.W,
    X: UiohookKey.X,
    Y: UiohookKey.Y,
    Z: UiohookKey.Z,
    Digit0: UiohookKey["0"],
    Digit1: UiohookKey["1"],
    Digit2: UiohookKey["2"],
    Digit3: UiohookKey["3"],
    Digit4: UiohookKey["4"],
    Digit5: UiohookKey["5"],
    Digit6: UiohookKey["6"],
    Digit7: UiohookKey["7"],
    Digit8: UiohookKey["8"],
    Digit9: UiohookKey["9"],
    "0": UiohookKey["0"],
    "1": UiohookKey["1"],
    "2": UiohookKey["2"],
    "3": UiohookKey["3"],
    "4": UiohookKey["4"],
    "5": UiohookKey["5"],
    "6": UiohookKey["6"],
    "7": UiohookKey["7"],
    "8": UiohookKey["8"],
    "9": UiohookKey["9"],
    F1: UiohookKey.F1,
    F2: UiohookKey.F2,
    F3: UiohookKey.F3,
    F4: UiohookKey.F4,
    F5: UiohookKey.F5,
    F6: UiohookKey.F6,
    F7: UiohookKey.F7,
    F8: UiohookKey.F8,
    F9: UiohookKey.F9,
    F10: UiohookKey.F10,
    F11: UiohookKey.F11,
    F12: UiohookKey.F12,
    Space: UiohookKey.Space,
    Tab: UiohookKey.Tab,
    Enter: UiohookKey.Enter,
    Escape: UiohookKey.Escape,
    Backspace: UiohookKey.Backspace,
    Delete: UiohookKey.Delete,
    Insert: UiohookKey.Insert,
    Home: UiohookKey.Home,
    End: UiohookKey.End,
    PageUp: UiohookKey.PageUp,
    PageDown: UiohookKey.PageDown,
    ArrowUp: UiohookKey.ArrowUp,
    ArrowDown: UiohookKey.ArrowDown,
    ArrowLeft: UiohookKey.ArrowLeft,
    ArrowRight: UiohookKey.ArrowRight,
    Minus: UiohookKey.Minus,
    Equal: UiohookKey.Equal,
    BracketLeft: UiohookKey.BracketLeft,
    BracketRight: UiohookKey.BracketRight,
    Backslash: UiohookKey.Backslash,
    Semicolon: UiohookKey.Semicolon,
    Quote: UiohookKey.Quote,
    Comma: UiohookKey.Comma,
    Period: UiohookKey.Period,
    Slash: UiohookKey.Slash,
    Backquote: UiohookKey.Backquote,
  };

  if (table[n] !== undefined) return table[n];
  if (/^[0-9]$/.test(n) && table[`Digit${n}`] !== undefined) return table[`Digit${n}`];
  return null;
}
