import { UiohookKey } from "uiohook-napi";

/** Физические сканкоды → символы русской раскладки ЙЦУКЕН (Windows/macOS/Linux). */
const JCUKEN_LOWER: Partial<Record<number, string>> = {
  [UiohookKey.Q]: "й",
  [UiohookKey.W]: "ц",
  [UiohookKey.E]: "у",
  [UiohookKey.R]: "к",
  [UiohookKey.T]: "е",
  [UiohookKey.Y]: "н",
  [UiohookKey.U]: "г",
  [UiohookKey.I]: "ш",
  [UiohookKey.O]: "щ",
  [UiohookKey.P]: "з",
  [UiohookKey.BracketLeft]: "х",
  [UiohookKey.BracketRight]: "ъ",
  [UiohookKey.A]: "ф",
  [UiohookKey.S]: "ы",
  [UiohookKey.D]: "в",
  [UiohookKey.F]: "а",
  [UiohookKey.G]: "п",
  [UiohookKey.H]: "р",
  [UiohookKey.J]: "о",
  [UiohookKey.K]: "л",
  [UiohookKey.L]: "д",
  [UiohookKey.Semicolon]: "ж",
  [UiohookKey.Quote]: "э",
  [UiohookKey.Z]: "я",
  [UiohookKey.X]: "ч",
  [UiohookKey.C]: "с",
  [UiohookKey.V]: "м",
  [UiohookKey.B]: "и",
  [UiohookKey.N]: "т",
  [UiohookKey.M]: "ь",
  [UiohookKey.Comma]: "б",
  [UiohookKey.Period]: "ю",
  [UiohookKey.Slash]: ".",
  [UiohookKey.Backquote]: "ё",
  [UiohookKey["1"]]: "1",
  [UiohookKey["2"]]: "2",
  [UiohookKey["3"]]: "3",
  [UiohookKey["4"]]: "4",
  [UiohookKey["5"]]: "5",
  [UiohookKey["6"]]: "6",
  [UiohookKey["7"]]: "7",
  [UiohookKey["8"]]: "8",
  [UiohookKey["9"]]: "9",
  [UiohookKey["0"]]: "0",
  [UiohookKey.Minus]: "-",
  [UiohookKey.Equal]: "=",
  [UiohookKey.Backslash]: "\\",
};

const JCUKEN_SHIFT: Partial<Record<number, string>> = {
  [UiohookKey.Q]: "Й",
  [UiohookKey.W]: "Ц",
  [UiohookKey.E]: "У",
  [UiohookKey.R]: "К",
  [UiohookKey.T]: "Е",
  [UiohookKey.Y]: "Н",
  [UiohookKey.U]: "Г",
  [UiohookKey.I]: "Ш",
  [UiohookKey.O]: "Щ",
  [UiohookKey.P]: "З",
  [UiohookKey.BracketLeft]: "Х",
  [UiohookKey.BracketRight]: "Ъ",
  [UiohookKey.A]: "Ф",
  [UiohookKey.S]: "Ы",
  [UiohookKey.D]: "В",
  [UiohookKey.F]: "А",
  [UiohookKey.G]: "П",
  [UiohookKey.H]: "Р",
  [UiohookKey.J]: "О",
  [UiohookKey.K]: "Л",
  [UiohookKey.L]: "Д",
  [UiohookKey.Semicolon]: "Ж",
  [UiohookKey.Quote]: "Э",
  [UiohookKey.Z]: "Я",
  [UiohookKey.X]: "Ч",
  [UiohookKey.C]: "С",
  [UiohookKey.V]: "М",
  [UiohookKey.B]: "И",
  [UiohookKey.N]: "Т",
  [UiohookKey.M]: "Ь",
  [UiohookKey.Comma]: "Б",
  [UiohookKey.Period]: "Ю",
  [UiohookKey.Slash]: ",",
  [UiohookKey.Backquote]: "Ё",
  [UiohookKey["1"]]: "!",
  [UiohookKey["2"]]: '"',
  [UiohookKey["3"]]: "№",
  [UiohookKey["4"]]: ";",
  [UiohookKey["5"]]: "%",
  [UiohookKey["6"]]: ":",
  [UiohookKey["7"]]: "?",
  [UiohookKey["8"]]: "*",
  [UiohookKey["9"]]: "(",
  [UiohookKey["0"]]: ")",
  [UiohookKey.Minus]: "_",
  [UiohookKey.Equal]: "+",
  [UiohookKey.Backslash]: "/",
};

const QWERTY_LOWER: Partial<Record<number, string>> = {
  [UiohookKey.A]: "a",
  [UiohookKey.B]: "b",
  [UiohookKey.C]: "c",
  [UiohookKey.D]: "d",
  [UiohookKey.E]: "e",
  [UiohookKey.F]: "f",
  [UiohookKey.G]: "g",
  [UiohookKey.H]: "h",
  [UiohookKey.I]: "i",
  [UiohookKey.J]: "j",
  [UiohookKey.K]: "k",
  [UiohookKey.L]: "l",
  [UiohookKey.M]: "m",
  [UiohookKey.N]: "n",
  [UiohookKey.O]: "o",
  [UiohookKey.P]: "p",
  [UiohookKey.Q]: "q",
  [UiohookKey.R]: "r",
  [UiohookKey.S]: "s",
  [UiohookKey.T]: "t",
  [UiohookKey.U]: "u",
  [UiohookKey.V]: "v",
  [UiohookKey.W]: "w",
  [UiohookKey.X]: "x",
  [UiohookKey.Y]: "y",
  [UiohookKey.Z]: "z",
  [UiohookKey["1"]]: "1",
  [UiohookKey["2"]]: "2",
  [UiohookKey["3"]]: "3",
  [UiohookKey["4"]]: "4",
  [UiohookKey["5"]]: "5",
  [UiohookKey["6"]]: "6",
  [UiohookKey["7"]]: "7",
  [UiohookKey["8"]]: "8",
  [UiohookKey["9"]]: "9",
  [UiohookKey["0"]]: "0",
  [UiohookKey.Minus]: "-",
  [UiohookKey.Equal]: "=",
  [UiohookKey.BracketLeft]: "[",
  [UiohookKey.BracketRight]: "]",
  [UiohookKey.Backslash]: "\\",
  [UiohookKey.Semicolon]: ";",
  [UiohookKey.Quote]: "'",
  [UiohookKey.Comma]: ",",
  [UiohookKey.Period]: ".",
  [UiohookKey.Slash]: "/",
  [UiohookKey.Backquote]: "`",
};

const QWERTY_SHIFT: Partial<Record<number, string>> = {
  [UiohookKey.A]: "A",
  [UiohookKey.B]: "B",
  [UiohookKey.C]: "C",
  [UiohookKey.D]: "D",
  [UiohookKey.E]: "E",
  [UiohookKey.F]: "F",
  [UiohookKey.G]: "G",
  [UiohookKey.H]: "H",
  [UiohookKey.I]: "I",
  [UiohookKey.J]: "J",
  [UiohookKey.K]: "K",
  [UiohookKey.L]: "L",
  [UiohookKey.M]: "M",
  [UiohookKey.N]: "N",
  [UiohookKey.O]: "O",
  [UiohookKey.P]: "P",
  [UiohookKey.Q]: "Q",
  [UiohookKey.R]: "R",
  [UiohookKey.S]: "S",
  [UiohookKey.T]: "T",
  [UiohookKey.U]: "U",
  [UiohookKey.V]: "V",
  [UiohookKey.W]: "W",
  [UiohookKey.X]: "X",
  [UiohookKey.Y]: "Y",
  [UiohookKey.Z]: "Z",
  [UiohookKey["1"]]: "!",
  [UiohookKey["2"]]: "@",
  [UiohookKey["3"]]: "#",
  [UiohookKey["4"]]: "$",
  [UiohookKey["5"]]: "%",
  [UiohookKey["6"]]: "^",
  [UiohookKey["7"]]: "&",
  [UiohookKey["8"]]: "*",
  [UiohookKey["9"]]: "(",
  [UiohookKey["0"]]: ")",
  [UiohookKey.Minus]: "_",
  [UiohookKey.Equal]: "+",
  [UiohookKey.BracketLeft]: "{",
  [UiohookKey.BracketRight]: "}",
  [UiohookKey.Backslash]: "|",
  [UiohookKey.Semicolon]: ":",
  [UiohookKey.Quote]: '"',
  [UiohookKey.Comma]: "<",
  [UiohookKey.Period]: ">",
  [UiohookKey.Slash]: "?",
  [UiohookKey.Backquote]: "~",
};

export function charFromKeycode(
  keycode: number,
  shift: boolean,
  layout: "jcuken" | "qwerty",
): string | null {
  if (layout === "jcuken") {
    return (shift ? JCUKEN_SHIFT[keycode] : JCUKEN_LOWER[keycode]) ?? null;
  }
  return (shift ? QWERTY_SHIFT[keycode] : QWERTY_LOWER[keycode]) ?? null;
}
